#!/usr/bin/env bash
# Турнкей-установка офлайн голосового ассистента:
#   venv + faster-whisper (STT) + Silero (TTS) + llama.cpp + Gemma-2-9B (LLM).
#
#   bash examples/setup-offline.sh
#
# После установки:
#   bash examples/start-offline-stack.sh   # llama-server + бот
#   bash examples/test-offline.sh          # smoke-тест всех компонентов
#
# GPU: скрипт ставит CUDA-сборку torch и cu12-библиотеки для CTranslate2.
# Без GPU faster-whisper/Silero сработают на CPU (медленнее) — задайте
# FW_DEVICE=cpu / SILERO_DEVICE=cpu в examples/offline.env.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DATA_DIR="${SMITHS_DATA:-$HOME/.local/share/smiths-net}"
MODELS_DIR="$DATA_DIR/models"
BIN_DIR="$DATA_DIR/llama-bin"
VENV="$ROOT/.venv"
PYTHON="$VENV/bin/python"
PIP="$VENV/bin/pip"

# Gemma-2-9B-it Q4_K_M (~5.6 ГБ) — заметно лучше по-русски, чем 2B, и
# помещается на 12 ГБ GPU рядом с whisper large-v3 (int8_float16) + Silero.
GEMMA_GGUF="$MODELS_DIR/gemma-2-9b-it-Q4_K_M.gguf"
GEMMA_URL="https://huggingface.co/bartowski/gemma-2-9b-it-GGUF/resolve/main/gemma-2-9b-it-Q4_K_M.gguf"

# llama.cpp prebuilt. ubuntu-x64 — CPU/Vulkan; для NVIDIA замените на
# CUDA-сборку (см. https://github.com/ggml-org/llama.cpp/releases).
LLAMA_RELEASE="${LLAMA_RELEASE:-b9718}"
LLAMA_TAR="llama-${LLAMA_RELEASE}-bin-ubuntu-x64.tar.gz"
LLAMA_URL="https://github.com/ggml-org/llama.cpp/releases/download/${LLAMA_RELEASE}/${LLAMA_TAR}"
LLAMACPP_PORT="${LLAMACPP_PORT:-8081}"

# Silero v5 русская модель (~150 МБ).
SILERO_MODEL_URL="https://models.silero.ai/models/tts/ru/v5_5_ru.pt"

log() { echo "[setup-offline] $*"; }

# ── 1. Python venv + зависимости ─────────────────────────────────
if [[ ! -x "$PYTHON" ]]; then
  log "creating venv at $VENV"
  python3 -m venv "$VENV"
fi
"$PIP" install --upgrade pip wheel -q

log "installing torch (CUDA) + faster-whisper + silero…"
"$PIP" install torch -q
"$PIP" install faster-whisper -q
"$PIP" install silero -q
# CTranslate2 (внутри faster-whisper) линкует cuBLAS/cuDNN из CUDA-12;
# torch может ставить cu13 — добавляем совместимые cu12-колёса.
log "installing CUDA-12 cuBLAS/cuDNN wheels for CTranslate2…"
"$PIP" install nvidia-cublas-cu12 nvidia-cudnn-cu12 -q || \
  log "WARN: cu12 wheels failed — faster-whisper may need FW_DEVICE=cpu"

# Silero model cache.
SILERO_DIR="$("$PYTHON" -c 'import silero,os;print(os.path.join(os.path.dirname(silero.__file__),"model"))' 2>/dev/null || true)"
if [[ -n "$SILERO_DIR" ]]; then
  mkdir -p "$SILERO_DIR"
  if [[ ! -s "$SILERO_DIR/v5_5_ru.pt" ]]; then
    log "downloading Silero v5_5_ru model (~150 MB)…"
    curl -L --retry 3 --progress-bar -o "$SILERO_DIR/v5_5_ru.pt" "$SILERO_MODEL_URL" \
      || rm -f "$SILERO_DIR/v5_5_ru.pt"
  fi
fi

# ── 2. Plugin shebangs → venv python ─────────────────────────────
patch_shebang() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  sed -i "1s|^#!/usr/bin/env python3.*|#!$PYTHON|" "$f"
  chmod +x "$f"
}
patch_shebang plugins/examples/ai-asr-faster-whisper/main.py
patch_shebang plugins/examples/ai-tts-silero/main.py
patch_shebang plugins/examples/ai-llm-llamacpp/main.py

# faster-whisper large-v3 (~3 ГБ) скачается автоматически при первом
# запросе в FW_DOWNLOAD_ROOT; явная предзагрузка не требуется.

# ── 3. llama.cpp prebuilt + Gemma-2-9B ───────────────────────────
mkdir -p "$MODELS_DIR"
if [[ ! -x "$BIN_DIR/llama-server" ]]; then
  log "downloading llama.cpp ${LLAMA_RELEASE} prebuilt…"
  tmp="$(mktemp -d)"
  wget -q --show-progress -O "$tmp/$LLAMA_TAR" "$LLAMA_URL"
  rm -rf "$BIN_DIR" && mkdir -p "$BIN_DIR"
  tar -xzf "$tmp/$LLAMA_TAR" -C "$BIN_DIR"
  rm -rf "$tmp"
fi
log "llama-server → $BIN_DIR/llama-server"

if [[ ! -f "$GEMMA_GGUF" ]]; then
  log "downloading Gemma-2-9B-it Q4_K_M (~5.6 GB)…"
  wget -q --show-progress -O "$GEMMA_GGUF" "$GEMMA_URL"
fi
log "Gemma → $GEMMA_GGUF"

# ── 4. Generate examples/offline.env ─────────────────────────────
cat > examples/offline.env <<EOF
# Auto-generated by examples/setup-offline.sh
OFFLINE=1

ASR_PLUGIN=ai-asr-faster-whisper
FW_MODEL=large-v3
FW_DEVICE=cuda
FW_COMPUTE_TYPE=int8_float16
FW_LANG=ru
FW_BEAM_SIZE=5
FW_VAD=1
FW_INITIAL_PROMPT="Телефонный разговор на русском языке."

LLM_PLUGIN=ai-llm-llamacpp
LLAMACPP_HOST=http://127.0.0.1:$LLAMACPP_PORT
LLAMACPP_MODEL=gemma
LLAMACPP_MODEL_PATH=$GEMMA_GGUF
LLAMACPP_TIMEOUT_SECS=180
LLM_MAX_TOKENS=160
LLM_HISTORY_MSGS=6
LLM_WARMUP=1
LLAMACPP_NGL=99
LLAMACPP_CTX=2048

TTS_PLUGIN=ai-tts-silero
SILERO_TTS=1
SILERO_MODEL=v5_5_ru
SILERO_SPEAKER=xenia
SILERO_THREADS=4
SILERO_DEVICE=cuda

VAD_SILENCE_SECS=0.8
VAD_THRESHOLD=250
VAD_SPIKE_TOLERANCE=2
VAD_PRE_SPEECH_SECS=0.30
VAD_MIN_SPEECH_SECS=0.20
RECORD_SECS=10.0
VAD_SPECULATE_SILENCE_SECS=0.35

BARGE_IN=1
BARGE_THRESHOLD=900

BOT_CONFIG=examples/bot.toml
BOT_FILLERS_ENABLE=0

RTP_PRIME_SECS=0.4
GREETING_LEAD_SILENCE_SECS=0.3
BOT_MAX_TURNS=200
BOT_IDLE_TURNS_MAX=3
EOF
log "wrote examples/offline.env"

# ── 5. Generate start-llamacpp.sh (GPU-aware) ────────────────────
cat > examples/start-llamacpp.sh <<EOF
#!/usr/bin/env bash
set -euo pipefail
BIN_DIR="$BIN_DIR"
MODEL="\${LLAMACPP_MODEL_PATH:-$GEMMA_GGUF}"
PORT="\${LLAMACPP_PORT:-$LLAMACPP_PORT}"
CTX="\${LLAMACPP_CTX:-2048}"
NGL="\${LLAMACPP_NGL:-99}"
cd "\$BIN_DIR"
export LD_LIBRARY_PATH="\$BIN_DIR:\${LD_LIBRARY_PATH:-}"
exec ./llama-server -m "\$MODEL" --host 127.0.0.1 --port "\$PORT" \\
  -c "\$CTX" -ngl "\$NGL" -fa on --cont-batching --no-mmap --keep -1
EOF
chmod +x examples/start-llamacpp.sh

cat > examples/start-offline-stack.sh <<'STACK'
#!/usr/bin/env bash
# Start llama.cpp LLM server (background) then the ASR bot (foreground).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
if ! curl -sf http://127.0.0.1:8081/health >/dev/null 2>&1; then
  echo "[offline] starting llama.cpp on :8081…"
  nohup bash examples/start-llamacpp.sh > /tmp/llamacpp.log 2>&1 &
  for _ in $(seq 1 90); do
    curl -sf http://127.0.0.1:8081/health >/dev/null 2>&1 && break
    sleep 2
  done
  echo "[offline] llama.cpp ready (log: /tmp/llamacpp.log)"
else
  echo "[offline] llama.cpp already running"
fi
exec bash examples/restart-asr-bot.sh
STACK
chmod +x examples/start-offline-stack.sh

cat > examples/test-offline.sh <<'SMOKE'
#!/usr/bin/env bash
# Smoke-test the offline stack: faster-whisper, Silero, llama.cpp.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
set -a; source examples/offline.env; set +a
PY="$ROOT/.venv/bin/python"

echo "=== STT: faster-whisper ==="
"$PY" -c "from faster_whisper import WhisperModel; WhisperModel('${FW_MODEL:-large-v3}', device='${FW_DEVICE:-cuda}', compute_type='${FW_COMPUTE_TYPE:-int8_float16}'); print('faster-whisper OK')"

echo "=== TTS: Silero ==="
REQ='{"jsonrpc":"2.0","id":1,"method":"synthesize","params":{"text":"Привет","output":{"codec":"pcm_s16le","sample_rate":8000}}}'
echo "$REQ" | "$PY" plugins/examples/ai-tts-silero/main.py | "$PY" -c "import json,sys; r=json.load(sys.stdin); print('Silero OK:', r['result']['duration_ms'], 'ms')"

echo "=== LLM: llama.cpp Gemma ==="
curl -sf "$LLAMACPP_HOST/v1/chat/completions" \
  -H 'Content-Type: application/json' \
  -d '{"model":"gemma","messages":[{"role":"user","content":"Скажи одно слово: да"}],"max_tokens":16}' \
  | "$PY" -c "import json,sys; d=json.load(sys.stdin); print('LLM OK:', d['choices'][0]['message']['content'][:80])"

echo "=== All offline components OK ==="
SMOKE
chmod +x examples/test-offline.sh

log "done!"
echo ""
echo "  venv:    $VENV"
echo "  STT:     faster-whisper large-v3 (GPU)"
echo "  TTS:     Silero v5_5_ru"
echo "  LLM:     Gemma-2-9B-it @ http://127.0.0.1:$LLAMACPP_PORT"
echo "  config:  examples/offline.env"
echo ""
echo "Start:"
echo "  bash examples/start-offline-stack.sh    # llama + bot"
echo "  bash examples/test-offline.sh           # smoke test"
