[package]
name         = "smiths-wasm"
edition      = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }
license      = { workspace = true }
description  = "WASM plugin host: wasmtime engine, guest ABI, host functions."

[dependencies]
smiths-core  = { workspace = true }
smiths-proto = { workspace = true }

[lints]
workspace = true
